### ISSUE TITLE
Accessibility

### ISSUE THREAD

**Issue by ttraenkler** [WebAssemblySummit/webassemblysummit.github.io#10]
- make color contrast more readable while keeping a balanced look
- check overall page accessibility

**Comment by pranjal9599** [comment]
Hi i checked the overall page accessibility using lighthouse and axe. Increasing the text color alpha from 0.5 to 0.7 seems to fix the color contrast issues. And adding html lang attribute and aria fixes the other issues.

### Before:

<img width="1348" alt="image" src="https://user-images.githubusercontent.com/15066223/69827128-105ba280-123c-11ea-9e2a-900257ebe201.png">
<img width="686" alt="image" src="https://user-images.githubusercontent.com/15066223/69827157-28332680-123c-11ea-95bc-e01ee7ed117d.png">
<img width="991" alt="image" src="https://user-images.githubusercontent.com/15066223/69827392-3766a400-123d-11ea-9de7-d616292d99bf.png">


### After making those changes: 

<img width="1319" alt="image" src="https://user-images.githubusercontent.com/15066223/69827289-b27b8a80-123c-11ea-8130-c5636ef0769e.png">
<img width="759" alt="image" src="https://user-images.githubusercontent.com/15066223/69827303-c45d2d80-123c-11ea-8832-347f747a4d32.png">

**Comment by surma** [comment]
Wanna open a PR?

**Comment by ttraenkler** [comment]
@pranjal9599 thanks, approved
