### ISSUE TITLE
add links to CFP and registration

### ISSUE THREAD

**Issue by ashleygwilliams** [WebAssemblySummit/webassemblysummit.github.io#4]

**Comment by ashleygwilliams** [comment]
this is my proposal, very rough of course
<img width="394" alt="Screen Shot 2019-11-27 at 12 59 27 PM" src="https://user-images.githubusercontent.com/1163554/69752192-528ac400-1116-11ea-9a1d-5e72e9f0f0d3.png">

**Comment by torch2424** [comment]
Yes! I think this is great! @ashleygwilliams 

I think part of this implementation, should also be to remove the flexbox page centering, since this seems like it will have more vertical height than the current site does 😄

**Comment by ttraenkler** [comment]
> I think part of this implementation, should also be to remove the flexbox page centering, since this seems like it will have more vertical height than the current site does 😄

@torch2424 definitely

@ashleygwilliams regarding the proposed page layout I will focus on the lower part related to the task. i have created #9 for the proposed logo redesign.

**Comment by ttraenkler** [comment]
@pranjal9599 You made a nice proposa for the buttonsl in #9. Could you add a PR to add the buttons to the current design so we're not blocked until the logo ticket is finished?

**Comment by pranjal9599** [comment]
Yes apply for speaker should link to here https://docs.google.com/forms/d/e/1FAIpQLSdY82WK8eGSDro2qLwU63wbf8bTQhcSmSmmofY8QuQceS9Tag/viewform right ? 

Where should the tickets one link to?

**Comment by ttraenkler** [comment]
@pranjal9599 Thanks, I've created a PR with the links already. What country are you from (timezone)?

**Comment by pranjal9599** [comment]
@ttraenkler India I just woke up it's 6:55 here

**Comment by ttraenkler** [comment]
@pranjal9599 if you'd like join us on Discord http://discordapp.com/invite/nEFErF8

**Comment by ttraenkler** [comment]
@pranjal9599 I just pushed the latest version to the redesign branch here
