### ISSUE TITLE
add CoC to site and repo

### ISSUE THREAD

**Issue by ashleygwilliams** [WebAssemblySummit/webassemblysummit.github.io#5]

**Comment by natorion** [comment]
I think we agreed to re-use the one from Rust Conf minus the Rust-specific parts: https://rustconf.com/about/

====
The WebAssembly Summit is intended to be an inclusive, welcoming conference for everyone. In particular, we do not tolerate harassment of conference participants in any form. Conference participants violating these rules may be sanctioned or expelled from the conference at the discretion of the conference organizers.

Harassment includes disparaging verbal comments related to gender, gender identity and expression, sexual orientation, disability, physical appearance, body size, race, age, or religion; sexual images in public spaces; deliberate intimidation; stalking; sustained disruption of talks or other events; inappropriate physical contact; and unwelcome sexual attention. Participants asked to stop any harassing behavior are expected to comply immediately.

If a participant engages in harassing behavior, the conference organizers may take any action they deem appropriate, including warning the offender or expulsion from the conference with no refund. If you are being harassed, notice that someone else is being harassed, or have any other concerns, please contact a member of conference staff immediately.

On-site, conference staff will be identifiable by their differently colored badges and tshirts (details on this will follow). If you need help of any kind, to report a bad situation, or anything else not specified that we can help with, please find us on site. For less urgent matters, or advance matters, please email us.

=======
Questions:
- Can we simply copy it?
- Should we replace conference with summit?
