### ISSUE TITLE
add contact  email

### ISSUE THREAD

**Issue by ashleygwilliams** [WebAssemblySummit/webassemblysummit.github.io#6]

**Comment by torch2424** [comment]
I can take this, will mock up a design and ask for feedback here 😄

**Comment by torch2424** [comment]
Used Devtools to add a link below the Sign up for Updates 😄 

And since [Chrome seems to require some setup to handle mailto links](https://support.google.com/chrome/thread/2305270?hl=en), I think it's worth putting the actual contact email 👍 

cc @ashleygwilliams @ttraenkler 

<img width="382" alt="Screen Shot 2019-11-27 at 11 08 45 AM" src="https://user-images.githubusercontent.com/1448289/69752549-5282c800-1106-11ea-867d-3453aa0cf06c.png">
<img width="1130" alt="Screen Shot 2019-11-27 at 11 08 22 AM" src="https://user-images.githubusercontent.com/1448289/69752551-531b5e80-1106-11ea-94c4-10bcf74c79ef.png">

**Comment by ashleygwilliams** [comment]
i would potentially try to widen this component- no real need for this content to be this narrow. and then potentially center it. i'd probably also give it some breathing room above and potentially  a horizontal rule (thin white?) just above

**Comment by ashleygwilliams** [comment]
also +1  to showing the actual email

**Comment by torch2424** [comment]
@ashleygwilliams Sounds good to me! 😄 

So like this than?

<img width="392" alt="Screen Shot 2019-11-27 at 11 58 10 AM" src="https://user-images.githubusercontent.com/1448289/69755513-3c2c3a80-110d-11ea-9837-a0d495724097.png">
<img width="864" alt="Screen Shot 2019-11-27 at 11 58 01 AM" src="https://user-images.githubusercontent.com/1448289/69755514-3c2c3a80-110d-11ea-8744-f6331f76c0cd.png">

**Comment by ttraenkler** [comment]
@torch2424 I would recommend to tone down the bar a bit, give it more vertical margin and make the link in a less salient shade.

**Comment by ttraenkler** [comment]
Regarding the flyer above, I'm not sure if @ashleygwilliams actually meant to widen it as well. To me the alignment was better before.

**Comment by torch2424** [comment]
So like this than? @ttraenkler @ashleygwilliams 😄 

<img width="378" alt="Screen Shot 2019-11-27 at 12 11 25 PM" src="https://user-images.githubusercontent.com/1448289/69756312-11db7c80-110f-11ea-980f-1741ef2fe00b.png">
<img width="860" alt="Screen Shot 2019-11-27 at 12 11 17 PM" src="https://user-images.githubusercontent.com/1448289/69756313-11db7c80-110f-11ea-9096-42c49c77742c.png">

**Comment by ashleygwilliams** [comment]
i would make the bar thinner and give it a top margin  of like 2.5em i think - just give it some space between the sign up for updates and the hr

also i did mean we should widen it- if folks have a large screen the super narrow multi-line email feels a little unnecessarily difficult to read

**Comment by torch2424** [comment]
> i would make the bar thinner and give it a top margin of like 2.5em i think - just give it some space between the sign up for updates and the hr

Oops @ttraenkler  commented this as well, My bad I forgot to do so in my screenshots 😢 

Made the fixes!

<img width="397" alt="Screen Shot 2019-11-27 at 12 26 45 PM" src="https://user-images.githubusercontent.com/1448289/69757196-359fc200-1111-11ea-9eae-919917a36eec.png">
<img width="867" alt="Screen Shot 2019-11-27 at 12 26 40 PM" src="https://user-images.githubusercontent.com/1448289/69757197-359fc200-1111-11ea-8648-c040b9fb4ace.png">

**Comment by torch2424** [comment]
As discussed on discord, more top margin, less bottom margin 😄 

<img width="391" alt="Screen Shot 2019-11-27 at 12 33 58 PM" src="https://user-images.githubusercontent.com/1448289/69757598-3b49d780-1112-11ea-8fdc-83b9a90527e2.png">

<img width="1371" alt="Screen Shot 2019-11-27 at 12 33 52 PM" src="https://user-images.githubusercontent.com/1448289/69757600-3be26e00-1112-11ea-93ca-fbca66b51662.png">

**Comment by ttraenkler** [comment]
@torch2424: Like it overall, maybe try the bar with alpha of sth like 0.7?  What about "Contact us: "? may be a bit more concise and focus the page more on the key message

**Comment by torch2424** [comment]
Done @ttraenkler 😄 

<img width="865" alt="Screen Shot 2019-11-27 at 12 58 43 PM" src="https://user-images.githubusercontent.com/1448289/69758952-c4aed900-1115-11ea-9eda-c3f76740e704.png">
<img width="393" alt="Screen Shot 2019-11-27 at 12 58 52 PM" src="https://user-images.githubusercontent.com/1448289/69758953-c4aed900-1115-11ea-820e-c6a7e0fb46ac.png">

**Comment by ashleygwilliams** [comment]
i think we have consensus,  let's ship it
