### ISSUE TITLE
Logo / Flyer redesign

### ISSUE THREAD

**Issue by ttraenkler** [WebAssemblySummit/webassemblysummit.github.io#9]
The Logo and flyer should look nice and recognisable, convey the key details, be accessible and mobile friendly.

@ashleygwilliams proposed this overall page layout which might tie into this issue (see #4) <img width="394" alt="Screen Shot 2019-11-27 at 12 59 27 PM" src="https://user-images.githubusercontent.com/1163554/69752192-528ac400-1116-11ea-9a1d-5e72e9f0f0d3.png">

**Comment by ttraenkler** [comment]
logo proposal by @ashleygwilliams  ![](https://cdn.discordapp.com/attachments/648975690485596163/649349362400362537/Screen_Shot_2019-11-26_at_1.25.11_PM.png)

will refine it a bit to integrate into the page

**Comment by pranjal9599** [comment]
Thoughts on this rough re-design from sketch ?

![MacBook Pro - 1](https://user-images.githubusercontent.com/15066223/69829291-6719aa00-1245-11ea-9fdc-e981e63f3148.jpg)

![X - 1](https://user-images.githubusercontent.com/15066223/69829176-05f1d680-1245-11ea-923e-44e2c373efce.jpg)

**Comment by ttraenkler** [comment]
@pranjal9599 Thanks for the proposal! I like the buttons and the background idea. 

Regarding the buttons I feel they are cool, if you want please make for PR them in context of #4.

The logo and headline / subtitle font and sizing could need a bit refinement. Personally, I would prefer the old font for "WebAssembly Summit" and overall make the headline slightly bigger.

Regarding the logo layout, I would try to align the foot of the mountain with the bottom of the subtitle, make it slightly bigger and have the summit stretch slightly above the Headline top.

**Comment by torch2424** [comment]
+1 to what Thomas suggested,

but in general, I think this looks great! :smile: :tada:  Excited to see this after the suggestions!

**Comment by pranjal9599** [comment]
Hey i changed according to suggestions can i get the svg of the logo
![image](https://user-images.githubusercontent.com/15066223/69869864-2157f280-12d4-11ea-99d0-470214329181.png)

**Comment by ttraenkler** [comment]
[wasmsummit.svg.zip](https://github.com/WebAssemblySummit/webassemblysummit.github.io/files/3905286/wasmsummit.svg.zip)

**Comment by ttraenkler** [comment]
@pranjal9599 could you make test with the current font also?

**Comment by pranjal9599** [comment]
Yes, with current font

![image](https://user-images.githubusercontent.com/15066223/69871289-69791400-12d8-11ea-98b7-84986efe647d.png)

**Comment by ttraenkler** [comment]
@pranjal9599 They want to use the official spelling "WebAssembly" - one word with uppercase initials.

**Comment by ttraenkler** [comment]
otherwise to me it looks good and ready to ship - what about mobile?

**Comment by ttraenkler** [comment]
@pranjal9599 Could you make a branch for this or if not otherwise possible a fork so we can have a look at the code? 

@ashleygwilliams what do you think about @pranjal9599 design of your layout proposal / logo? Should he make PR?

**Comment by pranjal9599** [comment]
![image](https://user-images.githubusercontent.com/15066223/69872136-a80fce00-12da-11ea-9014-15594e6a8afb.png)
![image](https://user-images.githubusercontent.com/15066223/69872143-ae05af00-12da-11ea-9047-2727dbd82cac.png)

It looks like this currently in mobile. Yeah i made a fork already: https://github.com/pranjal9599/webassemblysummit.github.io/tree/redesign

**Comment by natorion** [comment]
This looks neat. Could you upload a version that removes the flag+flag pole from the logo? A flag implies that there is some possession-taking, which it is not. Also the style of the flag seems to be not compatible with the rest of the page.

**Comment by ttraenkler** [comment]
@natorion Agree the flag sticks a bit out of the design. +1 removing it.

@pranjal9599 Cool! some minor tweaks i have in mind, but these are not urgent. left aligning the text on mobile would look a bit more readable + uppercasing the S of summit since it's a headline and some slight refinement of spacing.

**Comment by pranjal9599** [comment]
@natorion 
![image](https://user-images.githubusercontent.com/15066223/69873763-34bc8b00-12df-11ea-8ebb-a5ddbd1f2309.png)

@ttraenkler Yes mobile version definitely needs spacing and alignment tweaks

**Comment by ttraenkler** [comment]
@pranjal9599 cool, looks quite clean already. just my 5 cents: i feel in the desktop version the headline font size could be a slight notch bigger and the description text and buttons are a bit close to each other. maybe we could try to very slightly reduce the top margin of the page to free some space?

**Comment by natorion** [comment]
Looks a lot better now, thanks. What are people's thoughts on the WA. should it fit into the Wasm purple space or is the current overflowing style fine?

**Comment by ttraenkler** [comment]
@natorion I think it can be fine given the Monday deadline. Personally i would try to play with increasing the size of the mountain and overlap it a bit with the headline as a background scenery and see if the logo and the headline can be integrated a bit. Maybe if you think this is a welcome refinement I will play with it over the week-end a bit when I am back to health.

**Comment by ttraenkler** [comment]
@ashleygwilliams @natorion could someone allow @pranjal9599 to create a branch + pr?

**Comment by ttraenkler** [comment]
@pranjal9599 I've checked out your branch, it seems the latest version was not pushed yet.

**Comment by ttraenkler** [comment]
<img width="1440" alt="Bildschirmfoto 2019-11-29 um 22 02 55" src="https://user-images.githubusercontent.com/347722/69889974-16ad5580-12f4-11ea-8785-14a5db5d5e1c.png">

**Comment by ttraenkler** [comment]
@pranjal9599 I've pushed your redesign branch from your fork into this repo. Let's sync our work and refine from here if you agree on the direction taken.

**Comment by torch2424** [comment]
Just wanted to chime in, I really enjoy this redesign! It has my approval one @ttraenkler comments are addressed!

And unfortunately, I think only @ashleygwilliams has the ability to add collaborators to the project, but it is the holidays in the states, so no worries on that!

But! @pranjal9599 should be able to create a PR from their fork. So we should be all good to go there! 😀

**Comment by ttraenkler** [comment]
@torch2424 I've already addressed those and pushed to the redesign branch in this repo. We need to refine a few things I mentioned in the PR still.

**Comment by ttraenkler** [comment]
I am going to solve the remaining points now (make links functional, mobile) so we're ready to ship for Monday as I might not find time tomorrow.

**Comment by pranjal9599** [comment]
It looks great @ttraenkler ok I'll sync

**Comment by ttraenkler** [comment]
Just pushed with fixes for mobile, and added missing links.
<img width="1440" alt="Bildschirmfoto 2019-11-30 um 03 35 56" src="https://user-images.githubusercontent.com/347722/69894640-90f4ce80-1322-11ea-8178-026e5b139604.png">

**Comment by pranjal9599** [comment]
Rebased my repo with this. Now it's looking great on mobile too 🎉

**Comment by ttraenkler** [comment]
@pranjal9599 cool, i think we're done - high five ✋

**Comment by pranjal9599** [comment]
@ttraenkler great 🤚

**Comment by natorion** [comment]
This looks marvelous. Wow! Thanks folks.

Ashley is indeed the right person regarding permissions on this repo.

Pranjal <notifications@github.com> schrieb am Sa., 30. Nov. 2019, 04:09:

**Comment by natorion** [comment]
Regarding"satellite conference to ..." Let's remove that:

1.) This Sounds Like it is associated with th CG, which it is not
2.) There is only a very small amount of audience overlap.

Thoughts?

**Comment by pranjal9599** [comment]
+1 on removing the CG thing i also feel it's confusing

**Comment by pranjal9599** [comment]
+1 on removing the cg thing i also feel it's confusing

**Comment by pranjal9599** [comment]
+1 on that

**Comment by ttraenkler** [comment]
@natorion Yeah I agree about the satellite. I was bouncing back and forth with this. I think however it would be nice to let people know about this. Any other suggestions? Until then I'll remove it

**Comment by ttraenkler** [comment]
Ship it?
<img width="1440" alt="Bildschirmfoto 2019-11-30 um 11 26 21" src="https://user-images.githubusercontent.com/347722/69899284-44ca7e00-1364-11ea-8aad-3b9a594d23fb.png">

**Comment by natorion** [comment]
LGTM

**Comment by ttraenkler** [comment]
mobile view:
<img width="322" alt="Bildschirmfoto 2019-11-30 um 18 49 07" src="https://user-images.githubusercontent.com/347722/69904065-39964300-13a2-11ea-832f-442452868013.png">

**Comment by natorion** [comment]
Looks great. One thing I noticed: the fill in the A of WA is blue, but likely should be purple.

**Comment by ttraenkler** [comment]
good catch, will fix

**Comment by ashleygwilliams** [comment]
Really loving the collab here! You have my +1 once the inner “A” color is changed! Let’s ship it! 🚀

**Comment by ttraenkler** [comment]
@ashleygwilliams sorry forgot to mention the A is already fixed

**Comment by ttraenkler** [comment]
A fix 👍 
<img width="1440" alt="Bildschirmfoto 2019-11-30 um 22 48 37" src="https://user-images.githubusercontent.com/347722/69906445-af5ed680-13c3-11ea-9307-08b0ce665d47.png">

**Comment by torch2424** [comment]
LGTM 😀👍

**Comment by ttraenkler** [comment]
Made use of the time waiting for the approval to refine the mobile layout so more fits on shorter screens (this is iPhone X form factor still, but even on say an iPhone 6 at least you see the first button 👍 
<img width="324" alt="Bildschirmfoto 2019-12-01 um 13 03 42" src="https://user-images.githubusercontent.com/347722/69913679-18356580-143b-11ea-84e2-422a6418f73b.png">

**Comment by ttraenkler** [comment]
thanks for merging. a little bonus - like this?
<img width="1440" alt="Bildschirmfoto 2019-12-01 um 22 40 33" src="https://user-images.githubusercontent.com/347722/69920941-fdd8a780-148d-11ea-99cc-c8fc9bafd55e.png">

**Comment by ttraenkler** [comment]
i agree with @ashleygwilliams  the nodge did not really work. 

next try: while the allusion is gone, it fixes the perception of the purple hill popping in and out of being a separate object or part of the mountain for me
<img width="1440" alt="Bildschirmfoto 2019-12-01 um 23 47 32" src="https://user-images.githubusercontent.com/347722/69921757-99214b00-1495-11ea-953c-096d5b5f3c9f.png">

**Comment by ttraenkler** [comment]
<img width="1440" alt="Bildschirmfoto 2019-12-02 um 00 57 47" src="https://user-images.githubusercontent.com/347722/69922697-efdf5280-149e-11ea-9eb4-0ade88a5c756.png">

**Comment by ttraenkler** [comment]
@torch2424 @ashleygwilliams pr updated

**Comment by ttraenkler** [comment]
since the people i asked preferred the old version basically reverted. only made the WA have a little more space and no gradient
<img width="1440" alt="Bildschirmfoto 2019-12-02 um 08 42 23" src="https://user-images.githubusercontent.com/347722/69939700-d19a4680-14e0-11ea-8040-f4855c449b49.png">
